 % -------------------------------------------------------------------------
% Headless generation script for CMake pipeline.
% Run via: matlab -batch "generate_tests"
% -------------------------------------------------------------------------

% Amount of random fuzz tests to generate
FUZZ_COUNT = 30;

fileID = fopen('test_generated.c', 'w');

% 2. Write the Unity Test File Boilerplate
fprintf(fileID, '// AUTO-GENERATED BY MATLAB - DO NOT EDIT\n');
fprintf(fileID, '#include <stdlib.h>\n');
fprintf(fileID, '#include "unity_fixture.h"\n');
fprintf(fileID, '#include <ccontrol/tf.h>\n\n');

fprintf(fileID, 'TEST_GROUP(GeneratedFuzz);\n\n');

fprintf(fileID, 'static ControlHandle ctx;\n');
fprintf(fileID, 'static void *p_pool, *s_pool;\n');
fprintf(fileID, 'TEST_SETUP(GeneratedFuzz) {\n');
fprintf(fileID, '    p_pool = malloc(1024); s_pool = malloc(1024);\n');
fprintf(fileID, '    Control_System_Init(&ctx, Control_Arena_Create(p_pool, 1024), Control_Arena_Create(s_pool, 1024));\n');
fprintf(fileID, '}\n');
fprintf(fileID, 'TEST_TEAR_DOWN(GeneratedFuzz) {\n');
fprintf(fileID, '    Control_System_DeInit(&ctx);\n');
fprintf(fileID, '    free(p_pool); free(s_pool);\n');
fprintf(fileID, '}\n\n');

test_names = {};

% =====================================================================
% 1. DETERMINISTIC TESTS
% =====================================================================
name = 'SimpleSeries';
write_unity_test(fileID, name, tf(1, [1 2]), tf(2, [1 3]));
test_names{end+1} = name;

name = 'MismatchedOrder';
write_unity_test(fileID, name, tf(1, [1 2]), tf([1 2], [1 3 4 5]));
test_names{end+1} = name;

% =====================================================================
% 2. FUZZ TESTS
% =====================================================================
for i = 1:FUZZ_COUNT
    G1 = tf(randi([-5, 5], 1, 2), randi([-5, 5], 1, 3));
    G2 = tf(randi([-5, 5], 1, 2), randi([-5, 5], 1, 3));

    name = sprintf('FuzzMultiply_%d', i);
    write_unity_test(fileID, name, G1, G2);
    test_names{end+1} = name;
end

% =====================================================================
% 3. GENERATE THE RUNNER
% =====================================================================
fprintf(fileID, '\nTEST_GROUP_RUNNER(GeneratedFuzz) {\n');
for i = 1:length(test_names)
    fprintf(fileID, '    RUN_TEST_CASE(GeneratedFuzz, %s);\n', test_names{i});
end
fprintf(fileID, '}\n');

fclose(fileID);

function write_unity_test(fileID, test_name, G1, G2)
    G_sys = series(G1, G2);
    fprintf(fileID, 'TEST(GeneratedFuzz, %s) {\n', test_name);

    [n_cell, d_cell] = tfdata(G1);
    num1 = n_cell{1}; den1 = d_cell{1};

    [n_cell, d_cell] = tfdata(G2);
    num2 = n_cell{1}; den2 = d_cell{1};

    [n_cell, d_cell] = tfdata(G_sys);
    num_exp = n_cell{1}; den_exp = d_cell{1};

    % STRIP LEADING ZEROS SO MATLAB MATCHES C EXACTLY
    num1 = strip_zeros(num1); den1 = strip_zeros(den1);
    num2 = strip_zeros(num2); den2 = strip_zeros(den2);
    num_exp = strip_zeros(num_exp); den_exp = strip_zeros(den_exp);

    % Write arrays in C
    fprintf(fileID, '    float n1[] = {'); fprintf(fileID, '%.6ff, ', num1); fprintf(fileID, '};\n');
    fprintf(fileID, '    float d1[] = {'); fprintf(fileID, '%.6ff, ', den1); fprintf(fileID, '};\n');
    fprintf(fileID, '    float n2[] = {'); fprintf(fileID, '%.6ff, ', num2); fprintf(fileID, '};\n');
    fprintf(fileID, '    float d2[] = {'); fprintf(fileID, '%.6ff, ', den2); fprintf(fileID, '};\n');

    fprintf(fileID, '    float n_exp[] = {'); fprintf(fileID, '%.6ff, ', num_exp); fprintf(fileID, '};\n');
    fprintf(fileID, '    float d_exp[] = {'); fprintf(fileID, '%.6ff, ', den_exp); fprintf(fileID, '};\n');

    % Write the C logic to test these arrays
    fprintf(fileID, '    ControlVec num1_v = Control_Poly_AllocPersistent(&ctx, n1, %d);\n', length(num1));
    fprintf(fileID, '    ControlVec dem1_v = Control_Poly_AllocPersistent(&ctx, d1, %d);\n', length(den1));
    fprintf(fileID, '    ControlTransferFunction tf1 = Control_TF_FromPoly(&num1_v, &dem1_v);\n');

    fprintf(fileID, '    ControlVec num2_v = Control_Poly_AllocPersistent(&ctx, n2, %d);\n', length(num2));
    fprintf(fileID, '    ControlVec dem2_v = Control_Poly_AllocPersistent(&ctx, d2, %d);\n', length(den2));
    fprintf(fileID, '    ControlTransferFunction tf2 = Control_TF_FromPoly(&num2_v, &dem2_v);\n');

    fprintf(fileID, '    ControlTransferFunction result = Control_TF_Multiply(&ctx, &tf1, &tf2);\n');

    % Write the Assertions using the EXACT true lengths
    fprintf(fileID, '    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, %d);\n', length(num_exp));
    fprintf(fileID, '    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.dem.coeffs, %d);\n', length(den_exp));

    % Assert that ccontrol calculated the size correctly
    fprintf(fileID, '    TEST_ASSERT_EQUAL_size_t(%d, result.num.size);\n', length(num_exp));
    fprintf(fileID, '    TEST_ASSERT_EQUAL_size_t(%d, result.dem.size);\n', length(den_exp));

    fprintf(fileID, '}\n\n');
end

function out_arr = strip_zeros(in_arr)
    idx = find(abs(in_arr) > 1e-10, 1, 'first');

    if isempty(idx)
        out_arr = 0;
    else
        out_arr = in_arr(idx:end);
    end
end
