% -------------------------------------------------------------------------
% Headless generation script for CMake pipeline.
% Run via: matlab -batch "test_vector_gen"
% -------------------------------------------------------------------------

fileID = fopen("matlab_test_data.h", "w");

fprintf(fileID, '#ifndef MATLAB_VECTORS_H\n');
fprintf(fileID, '#define MATLAB_VECTORS_H\n\n');
fprintf(fileID, '/* ===================================================\n');
fprintf(fileID, ' * AUTO-GENERATED BY MATLAB DURING CMAKE BUILD\n');
fprintf(fileID, ' * DO NOT EDIT THIS FILE MANUALLY.\n');
fprintf(fileID, ' * =================================================== */\n\n');

fprintf(fileID, '\n#endif // MATLAB_VECTORS_H\n');
fclose(fileID);