#ifndef MATLAB_VECTORS_H
#define MATLAB_VECTORS_H

/* ===================================================
 * AUTO-GENERATED BY MATLAB DURING CMAKE BUILD
 * DO NOT EDIT THIS FILE MANUALLY.
 * =================================================== */


#endif // MATLAB_VECTORS_H
