// AUTO-GENERATED BY MATLAB - DO NOT EDIT
#include <stdlib.h>
#include "unity_fixture.h"
#include <ccontrol/tf.h>

TEST_GROUP(GeneratedFuzz);

static ControlHandle ctx;
static void *p_pool, *s_pool;
TEST_SETUP(GeneratedFuzz) {
    p_pool = malloc(1024); s_pool = malloc(1024);
    Control_System_Init(&ctx, Control_Arena_Create(p_pool, 1024), Control_Arena_Create(s_pool, 1024));
}
TEST_TEAR_DOWN(GeneratedFuzz) {
    Control_System_DeInit(&ctx);
    free(p_pool); free(s_pool);
}

TEST(GeneratedFuzz, SimpleSeries) {
    float n1[] = {1.000000f, };
    float d1[] = {1.000000f, 2.000000f, };
    float n2[] = {2.000000f, };
    float d2[] = {1.000000f, 3.000000f, };
    float n_exp[] = {2.000000f, };
    float d_exp[] = {1.000000f, 5.000000f, 6.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 1);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 2);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 1);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 2);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 1);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 3);
    TEST_ASSERT_EQUAL_size_t(1, result.num.size);
    TEST_ASSERT_EQUAL_size_t(3, result.den.size);
}

TEST(GeneratedFuzz, MismatchedOrder) {
    float n1[] = {1.000000f, };
    float d1[] = {1.000000f, 2.000000f, };
    float n2[] = {1.000000f, 2.000000f, };
    float d2[] = {1.000000f, 3.000000f, 4.000000f, 5.000000f, };
    float n_exp[] = {1.000000f, 2.000000f, };
    float d_exp[] = {1.000000f, 5.000000f, 10.000000f, 13.000000f, 10.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 1);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 2);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 4);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 2);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(2, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_1) {
    float n1[] = {3.000000f, 4.000000f, };
    float d1[] = {-4.000000f, 5.000000f, 1.000000f, };
    float n2[] = {-4.000000f, -2.000000f, };
    float d2[] = {1.000000f, 5.000000f, 5.000000f, };
    float n_exp[] = {-12.000000f, -22.000000f, -8.000000f, };
    float d_exp[] = {-4.000000f, -15.000000f, 6.000000f, 30.000000f, 5.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_2) {
    float n1[] = {-4.000000f, 5.000000f, };
    float d1[] = {5.000000f, 0.000000f, 3.000000f, };
    float n2[] = {-4.000000f, -1.000000f, };
    float d2[] = {5.000000f, 3.000000f, 5.000000f, };
    float n_exp[] = {16.000000f, -16.000000f, -5.000000f, };
    float d_exp[] = {25.000000f, 15.000000f, 40.000000f, 9.000000f, 15.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_3) {
    float n1[] = {2.000000f, -5.000000f, };
    float d1[] = {4.000000f, 5.000000f, 2.000000f, };
    float n2[] = {3.000000f, 3.000000f, };
    float d2[] = {-1.000000f, 2.000000f, -4.000000f, };
    float n_exp[] = {6.000000f, -9.000000f, -15.000000f, };
    float d_exp[] = {-4.000000f, 3.000000f, -8.000000f, -16.000000f, -8.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_4) {
    float n1[] = {2.000000f, -5.000000f, };
    float d1[] = {-2.000000f, -5.000000f, -4.000000f, };
    float n2[] = {4.000000f, 2.000000f, };
    float d2[] = {-2.000000f, 5.000000f, -5.000000f, };
    float n_exp[] = {8.000000f, -16.000000f, -10.000000f, };
    float d_exp[] = {4.000000f, 0.000000f, -7.000000f, 5.000000f, 20.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_5) {
    float n1[] = {-1.000000f, -1.000000f, };
    float d1[] = {3.000000f, 3.000000f, -3.000000f, };
    float n2[] = {-1.000000f, };
    float d2[] = {2.000000f, 2.000000f, 3.000000f, };
    float n_exp[] = {1.000000f, 1.000000f, };
    float d_exp[] = {6.000000f, 12.000000f, 9.000000f, 3.000000f, -9.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 1);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 2);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(2, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_6) {
    float n1[] = {-2.000000f, 2.000000f, };
    float d1[] = {2.000000f, -4.000000f, -4.000000f, };
    float n2[] = {5.000000f, };
    float d2[] = {-2.000000f, 1.000000f, -3.000000f, };
    float n_exp[] = {-10.000000f, 10.000000f, };
    float d_exp[] = {-4.000000f, 10.000000f, -2.000000f, 8.000000f, 12.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 1);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 2);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(2, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_7) {
    float n1[] = {3.000000f, -3.000000f, };
    float d1[] = {2.000000f, 4.000000f, };
    float n2[] = {5.000000f, 1.000000f, };
    float d2[] = {-4.000000f, -4.000000f, -3.000000f, };
    float n_exp[] = {15.000000f, -12.000000f, -3.000000f, };
    float d_exp[] = {-8.000000f, -24.000000f, -22.000000f, -12.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 2);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 4);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(4, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_8) {
    float n1[] = {4.000000f, -3.000000f, };
    float d1[] = {3.000000f, -3.000000f, 5.000000f, };
    float n2[] = {-2.000000f, -3.000000f, };
    float d2[] = {-3.000000f, 1.000000f, 0.000000f, };
    float n_exp[] = {-8.000000f, -6.000000f, 9.000000f, };
    float d_exp[] = {-9.000000f, 12.000000f, -18.000000f, 5.000000f, 0.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_9) {
    float n1[] = {-2.000000f, 4.000000f, };
    float d1[] = {1.000000f, 1.000000f, 5.000000f, };
    float n2[] = {-2.000000f, 3.000000f, };
    float d2[] = {3.000000f, -1.000000f, 1.000000f, };
    float n_exp[] = {4.000000f, -14.000000f, 12.000000f, };
    float d_exp[] = {3.000000f, 2.000000f, 15.000000f, -4.000000f, 5.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_10) {
    float n1[] = {-5.000000f, -5.000000f, };
    float d1[] = {3.000000f, 5.000000f, };
    float n2[] = {-4.000000f, 1.000000f, };
    float d2[] = {-5.000000f, -2.000000f, };
    float n_exp[] = {20.000000f, 15.000000f, -5.000000f, };
    float d_exp[] = {-15.000000f, -31.000000f, -10.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 2);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 2);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 3);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(3, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_11) {
    float n1[] = {-4.000000f, 3.000000f, };
    float d1[] = {-2.000000f, 0.000000f, -4.000000f, };
    float n2[] = {1.000000f, -3.000000f, };
    float d2[] = {2.000000f, 2.000000f, 3.000000f, };
    float n_exp[] = {-4.000000f, 15.000000f, -9.000000f, };
    float d_exp[] = {-4.000000f, -4.000000f, -14.000000f, -8.000000f, -12.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_12) {
    float n1[] = {-1.000000f, -5.000000f, };
    float d1[] = {-3.000000f, 5.000000f, -4.000000f, };
    float n2[] = {4.000000f, 0.000000f, };
    float d2[] = {5.000000f, -5.000000f, -1.000000f, };
    float n_exp[] = {-4.000000f, -20.000000f, 0.000000f, };
    float d_exp[] = {-15.000000f, 40.000000f, -42.000000f, 15.000000f, 4.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_13) {
    float n1[] = {-4.000000f, 5.000000f, };
    float d1[] = {-5.000000f, 3.000000f, 3.000000f, };
    float n2[] = {4.000000f, -5.000000f, };
    float d2[] = {-1.000000f, -3.000000f, 3.000000f, };
    float n_exp[] = {-16.000000f, 40.000000f, -25.000000f, };
    float d_exp[] = {5.000000f, 12.000000f, -27.000000f, 0.000000f, 9.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_14) {
    float n1[] = {-1.000000f, 5.000000f, };
    float d1[] = {-3.000000f, -3.000000f, -4.000000f, };
    float n2[] = {-4.000000f, 4.000000f, };
    float d2[] = {1.000000f, 1.000000f, -4.000000f, };
    float n_exp[] = {4.000000f, -24.000000f, 20.000000f, };
    float d_exp[] = {-3.000000f, -6.000000f, 5.000000f, 8.000000f, 16.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_15) {
    float n1[] = {4.000000f, 1.000000f, };
    float d1[] = {-2.000000f, 0.000000f, -1.000000f, };
    float n2[] = {-5.000000f, -3.000000f, };
    float d2[] = {-4.000000f, -3.000000f, -3.000000f, };
    float n_exp[] = {-20.000000f, -17.000000f, -3.000000f, };
    float d_exp[] = {8.000000f, 6.000000f, 10.000000f, 3.000000f, 3.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_16) {
    float n1[] = {-1.000000f, -5.000000f, };
    float d1[] = {4.000000f, 5.000000f, 0.000000f, };
    float n2[] = {-2.000000f, };
    float d2[] = {4.000000f, -1.000000f, -4.000000f, };
    float n_exp[] = {2.000000f, 10.000000f, };
    float d_exp[] = {16.000000f, 16.000000f, -21.000000f, -20.000000f, 0.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 1);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 2);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(2, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_17) {
    float n1[] = {3.000000f, -1.000000f, };
    float d1[] = {-3.000000f, -1.000000f, -4.000000f, };
    float n2[] = {-4.000000f, 5.000000f, };
    float d2[] = {5.000000f, 1.000000f, -5.000000f, };
    float n_exp[] = {-12.000000f, 19.000000f, -5.000000f, };
    float d_exp[] = {-15.000000f, -8.000000f, -6.000000f, 1.000000f, 20.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_18) {
    float n1[] = {-3.000000f, -2.000000f, };
    float d1[] = {4.000000f, -5.000000f, -5.000000f, };
    float n2[] = {-4.000000f, 2.000000f, };
    float d2[] = {3.000000f, 2.000000f, -1.000000f, };
    float n_exp[] = {12.000000f, 2.000000f, -4.000000f, };
    float d_exp[] = {12.000000f, -7.000000f, -29.000000f, -5.000000f, 5.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_19) {
    float n1[] = {1.000000f, -2.000000f, };
    float d1[] = {3.000000f, -3.000000f, 2.000000f, };
    float n2[] = {-3.000000f, -1.000000f, };
    float d2[] = {1.000000f, 3.000000f, -5.000000f, };
    float n_exp[] = {-3.000000f, 5.000000f, 2.000000f, };
    float d_exp[] = {3.000000f, 6.000000f, -22.000000f, 21.000000f, -10.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_20) {
    float n1[] = {5.000000f, 3.000000f, };
    float d1[] = {-1.000000f, -1.000000f, };
    float n2[] = {-2.000000f, 0.000000f, };
    float d2[] = {3.000000f, 3.000000f, };
    float n_exp[] = {-10.000000f, -6.000000f, 0.000000f, };
    float d_exp[] = {-3.000000f, -6.000000f, -3.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 2);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 2);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 3);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(3, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_21) {
    float n1[] = {2.000000f, -1.000000f, };
    float d1[] = {3.000000f, 0.000000f, -2.000000f, };
    float n2[] = {5.000000f, 4.000000f, };
    float d2[] = {1.000000f, 1.000000f, 1.000000f, };
    float n_exp[] = {10.000000f, 3.000000f, -4.000000f, };
    float d_exp[] = {3.000000f, 3.000000f, 1.000000f, -2.000000f, -2.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_22) {
    float n1[] = {-3.000000f, -2.000000f, };
    float d1[] = {-3.000000f, 4.000000f, };
    float n2[] = {-3.000000f, -3.000000f, };
    float d2[] = {-4.000000f, -3.000000f, -1.000000f, };
    float n_exp[] = {9.000000f, 15.000000f, 6.000000f, };
    float d_exp[] = {12.000000f, -7.000000f, -9.000000f, -4.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 2);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 4);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(4, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_23) {
    float n1[] = {-2.000000f, 5.000000f, };
    float d1[] = {-1.000000f, -3.000000f, 4.000000f, };
    float n2[] = {5.000000f, -1.000000f, };
    float d2[] = {-4.000000f, -3.000000f, -1.000000f, };
    float n_exp[] = {-10.000000f, 27.000000f, -5.000000f, };
    float d_exp[] = {4.000000f, 15.000000f, -6.000000f, -9.000000f, -4.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_24) {
    float n1[] = {1.000000f, -3.000000f, };
    float d1[] = {1.000000f, 2.000000f, -3.000000f, };
    float n2[] = {-4.000000f, -2.000000f, };
    float d2[] = {-2.000000f, -1.000000f, 0.000000f, };
    float n_exp[] = {-4.000000f, 10.000000f, 6.000000f, };
    float d_exp[] = {-2.000000f, -5.000000f, 4.000000f, 3.000000f, 0.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_25) {
    float n1[] = {-5.000000f, -3.000000f, };
    float d1[] = {3.000000f, -5.000000f, 5.000000f, };
    float n2[] = {3.000000f, 0.000000f, };
    float d2[] = {1.000000f, -3.000000f, 0.000000f, };
    float n_exp[] = {-15.000000f, -9.000000f, 0.000000f, };
    float d_exp[] = {3.000000f, -14.000000f, 20.000000f, -15.000000f, 0.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_26) {
    float n1[] = {5.000000f, 1.000000f, };
    float d1[] = {-3.000000f, 0.000000f, };
    float n2[] = {1.000000f, 2.000000f, };
    float d2[] = {-1.000000f, -1.000000f, 5.000000f, };
    float n_exp[] = {5.000000f, 11.000000f, 2.000000f, };
    float d_exp[] = {3.000000f, 3.000000f, -15.000000f, 0.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 2);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 4);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(4, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_27) {
    float n1[] = {-5.000000f, 4.000000f, };
    float d1[] = {5.000000f, 3.000000f, -4.000000f, };
    float n2[] = {-3.000000f, -2.000000f, };
    float d2[] = {2.000000f, -4.000000f, 2.000000f, };
    float n_exp[] = {15.000000f, -2.000000f, -8.000000f, };
    float d_exp[] = {10.000000f, -14.000000f, -10.000000f, 22.000000f, -8.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_28) {
    float n1[] = {-4.000000f, 2.000000f, };
    float d1[] = {3.000000f, 2.000000f, };
    float n2[] = {4.000000f, 4.000000f, };
    float d2[] = {-2.000000f, 2.000000f, -3.000000f, };
    float n_exp[] = {-16.000000f, -8.000000f, 8.000000f, };
    float d_exp[] = {-6.000000f, 2.000000f, -5.000000f, -6.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 2);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 4);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(4, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_29) {
    float n1[] = {-5.000000f, 3.000000f, };
    float d1[] = {4.000000f, };
    float n2[] = {1.000000f, 1.000000f, };
    float d2[] = {4.000000f, 3.000000f, 1.000000f, };
    float n_exp[] = {-5.000000f, -2.000000f, 3.000000f, };
    float d_exp[] = {16.000000f, 12.000000f, 4.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 1);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 3);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(3, result.den.size);
}

TEST(GeneratedFuzz, FuzzMultiply_30) {
    float n1[] = {-3.000000f, -3.000000f, };
    float d1[] = {4.000000f, -5.000000f, 0.000000f, };
    float n2[] = {-4.000000f, 5.000000f, };
    float d2[] = {2.000000f, 0.000000f, 0.000000f, };
    float n_exp[] = {12.000000f, -3.000000f, -15.000000f, };
    float d_exp[] = {8.000000f, -10.000000f, 0.000000f, 0.000000f, 0.000000f, };
    ControlVec num1_v = {0};
    ControlVec dem1_v = {0};
    ControlTransferFunction tf1 = {0};
    Control_Poly_AllocPersistent(&ctx, &num1_v, n1, 2);
    Control_Poly_AllocPersistent(&ctx, &dem1_v, d1, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf1, &num1_v, &dem1_v));
    ControlVec num2_v = {0};
    ControlVec dem2_v = {0};
    ControlTransferFunction tf2 = {0};
    Control_Poly_AllocPersistent(&ctx, &num2_v, n2, 2);
    Control_Poly_AllocPersistent(&ctx, &dem2_v, d2, 3);
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_FromPoly(&ctx, &tf2, &num2_v, &dem2_v));
    ControlTransferFunction result = {0};
    TEST_ASSERT_EQUAL(CCONTROL_OK, Control_TF_Multiply(&ctx, &result, &tf1, &tf2));
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(n_exp, result.num.coeffs, 3);
    TEST_ASSERT_EQUAL_FLOAT_ARRAY(d_exp, result.den.coeffs, 5);
    TEST_ASSERT_EQUAL_size_t(3, result.num.size);
    TEST_ASSERT_EQUAL_size_t(5, result.den.size);
}


TEST_GROUP_RUNNER(GeneratedFuzz) {
    RUN_TEST_CASE(GeneratedFuzz, SimpleSeries);
    RUN_TEST_CASE(GeneratedFuzz, MismatchedOrder);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_1);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_2);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_3);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_4);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_5);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_6);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_7);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_8);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_9);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_10);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_11);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_12);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_13);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_14);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_15);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_16);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_17);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_18);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_19);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_20);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_21);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_22);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_23);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_24);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_25);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_26);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_27);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_28);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_29);
    RUN_TEST_CASE(GeneratedFuzz, FuzzMultiply_30);
}
