name: AVR Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-avr:
    name: Build for AVR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instal AVR Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-avr avr-libc

      - name: Configure CMake
        run: >
          cmake -B build_avr
          -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/avr.cmake
          -DCMAKE_BUILD_TYPE=MinSizeRel

      - name: Build Controlly
        run: cmake --build build_avr --target controlly

      - name: Check footrprint
        run: avr-size -t build_avr/src/libcontrolly.a
