# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python Dependencieds
        run: pip install sphinx breathe sphinx-rtd-theme

      - name: Run Doxygen
        run: doxygen ./Doxyfile

      - name: Build Docs
        working-directory: ./docs
        run: |
          make html
          touch build/html/.nojekyll

      - name: Setup emsdk
        uses: emscripten-core/setup-emsdk@v15
        with:
          # Make sure to set a version number!
          version: 5.0.3
          # Optional emsdk version (set if not the same as emscripten version)
          #emsdk-version: 5.0.5
          # This is the name of the cache folder.
          # The cache folder will be placed in the build directory,
          #  so make sure it doesn't conflict with anything!
          actions-cache-folder: 'emsdk-cache'

      - name: Verify
        run: emcc -v

      - name: Create Build Directory
        run: mkdir build_web

      - name: Build and move files
        run: |
          cd build_web
          emcmake cmake .. -DCCONTROL_BUILD_EXAMPLES=ON
          cmake --build .
          mkdir -p ../docs/source/_static/wasm

          cp ./examples/raylib/statespace_second_order.js ../docs/source/_static/wasm/
          cp ./examples/raylib/statespace_second_order.wasm ../docs/source/_static/wasm/
          cp ./examples/raylib/statespace_second_order.html ../docs/source/_static/wasm/

          cp ./examples/raylib/pid_leader_follower.js ../docs/source/_static/wasm/
          cp ./examples/raylib/pid_leader_follower.wasm ../docs/source/_static/wasm/
          cp ./examples/raylib/pid_leader_follower.html ../docs/source/_static/wasm/


      - name: Upload Artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # This path must match where Sphinx outputs your HTML
          path: 'docs/build/html'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
